version: '3'
services:
  web:
    build: .
    ports:
      - 8069:8069
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backyard.rule=Host(`backyard.andrei.org.uk`) || Host(`backyard2023.andrei.org.uk`)"
      - "traefik.http.routers.backyard.tls=true"
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8070"
      - "--entrypoints.websecure.address=:8071"
      - "--providers.file.directory=/certs/"
      - "--providers.file.watch=true"
    ports:
      - "8070:8070"
      - "8071:8071"
    volumes:
      - /home/andreimv/docker_volumes/andrei-org-uk/:/certs/
      - /var/run/docker.sock:/var/run/docker.sock:ro
